[FEATURE] Criação de novo componente Sh3DataTableEditable #6
sh3-sistemas/components pull request #7
Opened 2024-09-25 20:22 UTC by guilherme-batista-sh3

## Descrição

Implementação de um novo componente Sh3DataTableEditable comforme issue #6.

### O que essa PR faz? 
Implementação de um novo componente Sh3DataTableEditable.

### Issue(s) Relacionada(s)
- Resolve #6 

---
## Alterações
### Tipo de mudança
> Por favor, apague as opções que não são relevantes.

- [ ] Correção de bug (mudança que corrige um problema)
- [x] Nova funcionalidade (mudança que adiciona uma nova funcionalidade)
- [ ] Atualização de documentação

### Checklist

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu realizei uma autoavaliação do meu próprio código.
- [ ] Comentei meu código, principalmente em áreas difíceis de entender.
- [ ] Fiz as alterações correspondentes na documentação.
- [x] Minhas mudanças não geram novas _warnings_.
- [ ] Adicionei testes que provam que a correção é eficaz ou que a funcionalidade funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações.

### Capturas de Tela (se aplicável)
![image](https://github.com/user-attachments/assets/9a7eae68-9df1-47af-a70b-2bc2ba0c9c8c)
DataTable
![image](https://github.com/user-attachments/assets/b2ab958c-564e-41f4-a454-2f04210a2ff1)
Criação de nova linha
![image](https://github.com/user-attachments/assets/ad5448c0-2fc7-4650-b782-686f8e18f92d)
Seleção de linhas

---
## Comentários Adicionais
> Adicione qualquer outro contexto ou informação aqui que possa ser útil para os revisores.

2024-10-01 17:05 UTC, barbara-b-boechat-sh3 requested changes

2024-10-01 17:05 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  }
Podemos trazer maior legibilidade pra esse trecho utilizando propriedades desestruturadas por exemplo:

```javascript 
props.columns.forEach(({ field, default: defaultValue }) => {
    if (defaultValue !== undefined) {
      newRow[field] = defaultValue;
    }
  });

```

Referência da desestruturação em Javascript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2024-10-01 17:05 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  selected.value = [];
Ao invés de utilizar uma simples operação de push no array foi utilizada essa sintaxe por qual motivo? Causar a reatividade do array e uma nova renderização no componente?

2024-10-01 19:44 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +        />
Corrigido.

2024-10-01 19:52 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +          }"
Corrigido.

2024-10-01 19:58 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  selected.value = [];
Corrigido.

2024-10-01 20:08 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +};
Corrigido.

2024-10-01 20:12 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +});
Usar `v-model` para conseguir manipular as listas dentro do componente `Sh3DataEditable.vue`.

2024-10-01 20:22 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  }
Corrigido.

2024-10-02 17:46 UTC, mariana-castro-sh3 requested changes

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  {{ value }}
Acho que esse `value` ficou esquecido aqui.. hehe

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +        borderTopColor: "#4ade80",
por que a cor é passada via #hex e não pelas variáveis do tailwind?

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +}
substitua essas functions por arrow functions para seguir o padrão do projeto

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +import type {
```suggestion
/**
 *
 * [Primevue Based](https://v3.primevue.org/datatable)
 * @module dataTables
 *
 */
import type {
```

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/types/index.ts
Nesse arquivo, é importante incluir as referências dos componentes (e do módulo) para fins de documentação. Deixei algumas sugestões pra te guiar 😸

2024-10-02 17:46 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +declare class Sh3DataTableEditable extends ClassComponent<
```suggestion
/**
 * **SH3 - Sh3DataTableEditable**
 *
 * _Editable Data Table is an extension to standard DataTable element with icons and theming._
 * --- ---
 * [Primevue Based Component](https://www.primevue.org)
 * @group Component
 *
 */
declare class Sh3DataTableEditable extends ClassComponent<
```

2024-10-02 17:49 UTC, mariana-castro-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +    text: "bg-green-400 text-xs rounded-md p-1.5",
substitua `green` por `grass`

2024-10-02 18:57 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +  {{ value }}
Corrigido.

2024-10-02 18:57 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +}
Corrigido.

2024-10-02 18:57 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +import type {
Corrigido.

2024-10-02 18:58 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/types/index.ts
> +declare class Sh3DataTableEditable extends ClassComponent<
Corrigido.

2024-10-02 18:59 UTC, guilherme-batista-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +    text: "bg-green-400 text-xs rounded-md p-1.5",
Corrigido.

2024-10-15 14:14 UTC, barbara-b-boechat-sh3 commented on src/components/Tables/DataTable/Sh3DataTableEditable.vue
> +        borderTopColor: "#4ade80",
Essa foi única maneira que o PrimeVue aceitou a mudança da cor, testamos com variaveis do tailwind mas não funciona.

2024-10-17 17:42 UTC, barbara-b-boechat-sh3 approved these changes

2024-10-17 17:44 UTC, mariana-castro-sh3 approved these changes

2024-10-17 18:05 UTC, merged